import { FunctionComponent, useEffect, useState } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import * as solidIcons from "@fortawesome/free-solid-svg-icons";
import * as brandIcons from "@fortawesome/free-brands-svg-icons";

const shuffle = <T extends unknown>(array: T[]): T[] => {
  const result = [...array];
  for (let i = result.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [result[i], result[j]] = [result[j], result[i]];
  }
  return result;
};

const IconBackground: FunctionComponent = () => {
  const [icons, setIcons] = useState<IconDefinition[]>([]);
  
  useEffect(() => {
    const iconsList: IconDefinition[] = [
      solidIcons.faAddressBook,
      solidIcons.faAddressBook,
      solidIcons.faAddressCard,
      solidIcons.faAddressCard,
      solidIcons.faArchive,
      solidIcons.faBalanceScale,
      solidIcons.faBalanceScaleLeft,
      solidIcons.faBalanceScaleRight,
      solidIcons.faBan,
      solidIcons.faBarcode,
      solidIcons.faBath,
      solidIcons.faBell,
      solidIcons.faBell,
      solidIcons.faBirthdayCake,
      brandIcons.faBitcoin,
      solidIcons.faBook,
      solidIcons.faBookmark,
      solidIcons.faBookmark,
      solidIcons.faBox,
      solidIcons.faBoxes,
      solidIcons.faBriefcase,
      brandIcons.faBtc,
      solidIcons.faBug,
      solidIcons.faBuilding,
      solidIcons.faBuilding,
      solidIcons.faBullhorn,
      solidIcons.faBullseye,
      solidIcons.faBusinessTime,
      solidIcons.faCalculator,
      solidIcons.faCalendar,
      solidIcons.faCalendar,
      solidIcons.faCalendarAlt,
      solidIcons.faCalendarAlt,
      solidIcons.faCamera,
      solidIcons.faCameraRetro,
      solidIcons.faCartArrowDown,
      solidIcons.faCartPlus,
      solidIcons.faCertificate,
      solidIcons.faChartArea,
      solidIcons.faChartBar,
      solidIcons.faChartBar,
      solidIcons.faChartLine,
      solidIcons.faChartPie,
      solidIcons.faCity,
      solidIcons.faClipboard,
      solidIcons.faClipboard,
      solidIcons.faClipboardCheck,
      solidIcons.faClipboardList,
      solidIcons.faClone,
      solidIcons.faClone,
      solidIcons.faCode,
      solidIcons.faCodeBranch,
      solidIcons.faCoffee,
      solidIcons.faColumns,
      solidIcons.faComment,
      solidIcons.faComment,
      solidIcons.faCommentAlt,
      solidIcons.faCommentAlt,
      solidIcons.faCommentDots,
      solidIcons.faCommentDots,
      solidIcons.faCommentMedical,
      solidIcons.faCommentSlash,
      solidIcons.faComments,
      solidIcons.faComments,
      solidIcons.faCompactDisc,
      solidIcons.faCompass,
      solidIcons.faCompass,
      solidIcons.faCopy,
      solidIcons.faCopy,
      solidIcons.faCopyright,
      solidIcons.faCopyright,
      solidIcons.faCreditCard,
      solidIcons.faCreditCard,
      solidIcons.faCut,
      solidIcons.faDatabase,
      solidIcons.faDesktop,
      solidIcons.faDollarSign,
      solidIcons.faDolly,
      solidIcons.faDollyFlatbed,
      solidIcons.faDoorClosed,
      solidIcons.faDoorOpen,
      solidIcons.faDownload,
      solidIcons.faDungeon,
      solidIcons.faEdit,
      solidIcons.faEdit,
      solidIcons.faEnvelope,
      solidIcons.faEnvelope,
      solidIcons.faEnvelopeOpen,
      solidIcons.faEnvelopeOpen,
      solidIcons.faEnvelopeSquare,
      solidIcons.faEraser,
      brandIcons.faEthereum,
      solidIcons.faEthernet,
      solidIcons.faEuroSign,
      solidIcons.faEye,
      solidIcons.faEye,
      solidIcons.faEyeSlash,
      solidIcons.faEyeSlash,
      solidIcons.faFax,
      solidIcons.faFile,
      solidIcons.faFile,
      solidIcons.faFileAlt,
      solidIcons.faFileAlt,
      solidIcons.faFileArchive,
      solidIcons.faFileArchive,
      solidIcons.faFileAudio,
      solidIcons.faFileAudio,
      solidIcons.faFileCode,
      solidIcons.faFileCode,
      solidIcons.faFileContract,
      solidIcons.faFileExcel,
      solidIcons.faFileExcel,
      solidIcons.faFileImage,
      solidIcons.faFileImage,
      solidIcons.faFilePdf,
      solidIcons.faFilePdf,
      solidIcons.faFilePowerpoint,
      solidIcons.faFilePowerpoint,
      solidIcons.faFileSignature,
      solidIcons.faFileVideo,
      solidIcons.faFileVideo,
      solidIcons.faFileWord,
      solidIcons.faFileWord,
      solidIcons.faFilter,
      solidIcons.faFingerprint,
      solidIcons.faFireExtinguisher,
      solidIcons.faFolder,
      solidIcons.faFolder,
      solidIcons.faFolderMinus,
      solidIcons.faFolderOpen,
      solidIcons.faFolderOpen,
      solidIcons.faFolderPlus,
      solidIcons.faFrown,
      solidIcons.faFrown,
      solidIcons.faGem,
      solidIcons.faGem,
      solidIcons.faGift,
      solidIcons.faGlasses,
      solidIcons.faGlobe,
      solidIcons.faHandshake,
      solidIcons.faHandshake,
      solidIcons.faHardHat,
      solidIcons.faHdd,
      solidIcons.faHdd,
      solidIcons.faHeadphones,
      solidIcons.faHeart,
      solidIcons.faHeart,
      solidIcons.faHighlighter,
      solidIcons.faHryvnia,
      solidIcons.faIcons,
      solidIcons.faIdBadge,
      solidIcons.faIdBadge,
      solidIcons.faIdCard,
      solidIcons.faIdCard,
      solidIcons.faIdCardAlt,
      solidIcons.faIndustry,
      solidIcons.faKey,
      solidIcons.faKeyboard,
      solidIcons.faKeyboard,
      solidIcons.faLandmark,
      solidIcons.faLaptop,
      solidIcons.faLaptopCode,
      solidIcons.faLaptopHouse,
      solidIcons.faLiraSign,
      solidIcons.faLock,
      solidIcons.faLockOpen,
      solidIcons.faMarker,
      solidIcons.faMask,
      solidIcons.faMeh,
      solidIcons.faMeh,
      solidIcons.faMemory,
      solidIcons.faMicrochip,
      solidIcons.faMobile,
      solidIcons.faMobileAlt,
      solidIcons.faMoneyBill,
      solidIcons.faMoneyBillAlt,
      solidIcons.faMoneyBillAlt,
      solidIcons.faMoneyBillWave,
      solidIcons.faMoneyBillWaveAlt,
      solidIcons.faMoneyCheck,
      solidIcons.faMoneyCheckAlt,
      solidIcons.faMouse,
      solidIcons.faPallet,
      solidIcons.faPaperclip,
      solidIcons.faPassport,
      solidIcons.faPaste,
      solidIcons.faPen,
      solidIcons.faPenAlt,
      solidIcons.faPenFancy,
      solidIcons.faPenNib,
      solidIcons.faPenSquare,
      solidIcons.faPencilAlt,
      solidIcons.faPercent,
      solidIcons.faPhone,
      solidIcons.faPhoneAlt,
      solidIcons.faPhoneSlash,
      solidIcons.faPhoneSquare,
      solidIcons.faPhoneSquareAlt,
      solidIcons.faPhoneVolume,
      solidIcons.faPhotoVideo,
      solidIcons.faPlug,
      solidIcons.faPoundSign,
      solidIcons.faPowerOff,
      solidIcons.faPrint,
      solidIcons.faProjectDiagram,
      solidIcons.faQrcode,
      solidIcons.faQuoteLeft,
      solidIcons.faQuoteRight,
      solidIcons.faReceipt,
      solidIcons.faRegistered,
      solidIcons.faRegistered,
      solidIcons.faRubleSign,
      solidIcons.faRupeeSign,
      solidIcons.faSatellite,
      solidIcons.faSatelliteDish,
      solidIcons.faSave,
      solidIcons.faSave,
      solidIcons.faSdCard,
      solidIcons.faServer,
      solidIcons.faShekelSign,
      solidIcons.faShieldAlt,
      solidIcons.faShippingFast,
      solidIcons.faShoppingBag,
      solidIcons.faShoppingBasket,
      solidIcons.faShoppingCart,
      solidIcons.faSimCard,
      solidIcons.faSitemap,
      solidIcons.faSmile,
      solidIcons.faSmile,
      solidIcons.faSms,
      solidIcons.faSocks,
      solidIcons.faStar,
      solidIcons.faStar,
      solidIcons.faStickyNote,
      solidIcons.faStickyNote,
      solidIcons.faStream,
      solidIcons.faTable,
      solidIcons.faTablet,
      solidIcons.faTabletAlt,
      solidIcons.faTag,
      solidIcons.faTags,
      solidIcons.faTasks,
      solidIcons.faTenge,
      solidIcons.faTerminal,
      solidIcons.faThumbsDown,
      solidIcons.faThumbsDown,
      solidIcons.faThumbsUp,
      solidIcons.faThumbsUp,
      solidIcons.faThumbtack,
      solidIcons.faTrademark,
      solidIcons.faTrophy,
      solidIcons.faTruck,
      solidIcons.faTv,
      solidIcons.faUnlock,
      solidIcons.faUnlockAlt,
      solidIcons.faUpload,
      solidIcons.faUserLock,
      solidIcons.faUserSecret,
      solidIcons.faUserShield,
      solidIcons.faVideo,
      solidIcons.faVideoSlash,
      solidIcons.faWallet,
      solidIcons.faWarehouse,
      solidIcons.faWindowClose,
      solidIcons.faWindowClose,
      solidIcons.faWindowMaximize,
      solidIcons.faWindowMaximize,
      solidIcons.faWindowMinimize,
      solidIcons.faWindowMinimize,
      solidIcons.faWindowRestore,
      solidIcons.faWindowRestore,
      solidIcons.faWonSign
    ];

    const shuffledIcons = shuffle(iconsList);
    
    const gridSize = 25 * 25;
    let iconGrid: IconDefinition[] = [];
    
    while (iconGrid.length < gridSize) {
      iconGrid = [...iconGrid, ...shuffledIcons];
    }
    
    setIcons(iconGrid.slice(0, gridSize));
  }, []);

  return (
    <div className="absolute inset-0 overflow-hidden pointer-events-none">
      <div className="grid-background">
        {icons.map((icon, index) => (
          <FontAwesomeIcon 
            key={index}
            icon={icon} 
            className="grid-icon"
          />
        ))}
      </div>
    </div>
  );
};

export default IconBackground; 